### ISSUE TITLE
Display executable icon instead of generic icon

### ISSUE THREAD

**Issue by chereskata** [fthx/window-title-is-back#1]
Thanks for your cool extension. I also miss the v44 app menu a lot. (The non clickable part, the active executable name in particular).

Unfortunately the program does not display the active window's icon (yet).

Current state:
![current](https://github.com/fthx/window-title-is-back/assets/87526889/33ce6c33-7ea9-4178-a778-a9ef9a565af6)

How i envision it (pre v45 basically):
![firefox](https://github.com/fthx/window-title-is-back/assets/87526889/8c7ae97e-436e-4c01-92f8-99af3d42c403)

**Comment by fthx** [comment]
TBH I was sure to have this feature request.
But finding the right app icon from a window instance is not so easy. I dit it in BaBar but here I rather think to remove the window-title symbolic icon.

I keep this request open to see if people really need this icon (personally I do not!).

**Comment by chereskata** [comment]
After thinking about it, only the window title / program name right of 
the workspaces indicator seems just right to me. The program name right 
of the "Activities" text would have looked odd, but this is a promising 
idea :).

**Comment by fthx** [comment]
Ok I made some prefs + UI so it's coming soon.
icon + app name + window title
on/off
