### ISSUE TITLE
Align context menu to left side

### ISSUE THREAD

**Issue by concept10** [fthx/window-title-is-back#10]
Since the size of window titles vary (and could be quite long in the case of for example Firefox browser tab titles), could you align the context menu to the left?  This would allow for a consistent target for the context menu versus it moving based on the length.

**Comment by fthx** [comment]
Yes, if it's easy I'll do it.

**Comment by fthx** [comment]
Nope, I don't know how to do that easily. I can recreate a menu and put it where I want (cf. DashBar) but that's clearly something I won't do here.

**Comment by fthx** [comment]
I finally found out how to do it.
https://github.com/fthx/window-title-is-back/commit/7da0b5c72e99515e2e09a56cc9d99abd464577f8

Feel free to reopen if needed.

**Comment by concept10** [comment]
Thanks very much!  🚀
