### ISSUE TITLE
Long title dosn't fit in panel

### ISSUE THREAD

**Issue by yellowpookie** [fthx/window-title-is-back#13]
Long title dosn't fit in panel. May be add option to cut it after N symbols?
Overflow behavior
![Снимок экрана от 2023-11-16 19-27-18](https://github.com/fthx/window-title-is-back/assets/1326818/c120681e-f634-4f49-882e-628d8e404caa)
Normal behavior
![Снимок экрана от 2023-11-16 19-27-33](https://github.com/fthx/window-title-is-back/assets/1326818/23396026-59ce-4132-a65d-5b59d057d58d)

**Comment by fthx** [comment]
That's because you use Dash to Panel or some similar extension.
There's no issue using Window title is back natively, the title is cropped.
So that's a bug in your other extension, that has to crop the box if too large.

**Comment by fthx** [comment]
![image](https://github.com/fthx/window-title-is-back/assets/23138504/3c72056a-9030-40d8-ab0c-64eac77baecf)
