### ISSUE TITLE
Is this extension able to remove title bars?

### ISSUE THREAD

**Issue by jcmolinajr** [fthx/window-title-is-back#14]
I was wondering if this  extension able to Remove title bars like https://extensions.gnome.org/extension/1732/gtk-title-bar/ used to do before GNOME 45?

**Comment by fthx** [comment]
No sorry and that's not planned, TBH!

**Comment by fthx** [comment]
I  don't even know if this is possible running Wayland.

**Comment by jcmolinajr** [comment]
Shame. Thanks for clearing that up!
