### ISSUE TITLE
Crossfade on app name change

### ISSUE THREAD

**Issue by Skaldebane** [fthx/window-title-is-back#15]
Copied from https://github.com/fthx/appmenu-is-back/issues/5.

**Comment by fthx** [comment]
https://github.com/fthx/window-title-is-back/commit/e64ace22236977a606873d3b59e1390c97fd7a1e

You can set the fade in/out time in prefs.

**Comment by fthx** [comment]
I changed the code too, moving some functions to indicator's class, that's cleaner now.

**Comment by Skaldebane** [comment]
Didn't notice this issue get closed until I actually saw the new fade! Thanks a lot!

**Comment by Skaldebane** [comment]
@fthx This works beautifully, however it has a side effect that sometimes the animation happens even without switching the application. e.g. in Firefox switching tabs causes it to fade out and in again. On Spotify, playing/pausing causes that too.

I guess this is because the animation is triggered when the window title changes (which is what happens when switching tabs on Firefox or pause/play on Spotify), but it looks weird when I have it setup to only show the app name (just "Firefox", instead of the window title).

This could be solved by either:
1. Using a crossfade for the animation instead of separate fade-in/out phases. The animation will still trigger, but will be _mostly unnoticeable_[^1] when the content hasn't changed, because both the old content and target content are visible and animating at the same time.
2. Trigger the animation only for changes in the visible content (e.g. if only the app name/icon are visible, don't trigger based on window title). This is obviously a lot more involved.

A third way is to merge both solutions, using a crossfade for title/icon changes for the same app (or window), but doing a full fade-out/fade-in when the whole app (or window) changes.

Anyways, this is not all that big of an issue, but I'll try messing around with and opening a PR if anything works.

[^1]: If the animation curve is not linear, the sum of both alphas will be a little less than 100% during the animation, which makes it slightly noticeable that a crossfade is happening.

**Comment by fthx** [comment]
If you don't use titles, you can set ease time tp 0 in prefs.
