### ISSUE TITLE
reduce the padding

### ISSUE THREAD

**Issue by alisson3000br** [fthx/window-title-is-back#17]
Hi, how can i reduce the padding as you see in the screenshot of "firefox" that is your extension. and the second screenshot which is another extension not yours which says "File" the padding is 0px. I wish i could so that too and also make it bold text 

![Screenshot from 2024-04-26 03-05-06](https://github.com/fthx/window-title-is-back/assets/148722558/d1767468-a8db-4237-9e35-b916c8202313)
![Screenshot from 2024-04-26 03-05-21](https://github.com/fthx/window-title-is-back/assets/148722558/4bcd2535-f7f8-47cf-a8cc-119af54cbb93)

**Comment by alisson3000br** [comment]
that color different from the panel color is because I hover the mouse on it, so that gray highlight as you see the "File" is 0px and the "Firefox" the highlight is above 10px

**Comment by alisson3000br** [comment]
it is called padding on Container i think

**Comment by fthx** [comment]
I don't get such a padding.
Looking at Places Menu official extension, I don't get a noticeable difference for padding.
Sufficient padding is necessary for some quite squared icons.
