### ISSUE TITLE
[Feature request] Trimming and filtering the title

### ISSUE THREAD

**Issue by rthrejheytjyrtj545** [fthx/window-title-is-back#19]
Firefox window titles include the application name, which causes duplication when the application name display setting is enabled. Also, site titles often become long and do not even fit into the entire space, causing the width to stretch right up to the clock and causing a visual imbalance on one side

The solution may be to set up a line limit of a certain number of characters or width in pixels, as well as exclusion filtering based on exact or regular expressions

**Comment by fthx** [comment]
Did you try Task Up extension?
Would it fit your needs if I would display only the focused window (needs a new setting)?

**Comment by fthx** [comment]
For sure I won't filter the titles since it's endless.
I see if I can set the width in % rather than in px.

**Comment by fthx** [comment]
https://github.com/fthx/window-title-is-back/commit/213e1e0bd434a6e3327073e13a0926921445c066
