### ISSUE TITLE
Display Name[$lang] from desktop file instead of pure window title

### ISSUE THREAD

**Issue by chereskata** [fthx/window-title-is-back#2]
My biggest usecase for AppMenu has been to differentiate between firefox and firefox esr windows. (Login / No login browser). Both browsers have "* - Mozilla Firefox" as their declared window title.

This has the following effects:

* It fills up the whole space between workspace indicator and clock, if the title happens to be long enough: 
  
![example](https://github.com/fthx/window-title-is-back/assets/87526889/1cd52b39-815a-49ba-91da-9d172ece3d95)

* If a window has no title, it's program name will not be displayed

I therefore think it is handy to use the executable name as defined in the `.desktop` files under Name=* as v44 and earlier did

Thank you!

**Comment by fthx** [comment]
Ok but that's not the goal of this extension ;-) .
Maybe another `App Menu is Back` extension...
Why not but not before november!

I'll have a look at displaying the app name at the right of the panel.

**Comment by fthx** [comment]
Maybe I can do something simple.

**Comment by chereskata** [comment]
Thank you for the effort! I thought of writing this "take back my 
AppMenu" extension myself, but i unfortunately have no experience of 
programming gnome-shell extensions.

**Comment by fthx** [comment]
Ok I made some prefs + UI so it's coming soon.
icon + app name + window title
on/off

**Comment by fthx** [comment]
uploaded, waiting for review:
https://extensions.gnome.org/review/45595

**Comment by chereskata** [comment]
Works like a charm! Thank you!
