### ISSUE TITLE
Width doesn't adjust to title content

### ISSUE THREAD

**Issue by Wedaxi** [fthx/window-title-is-back#21]
On v30 version of the extension the width doesn't adjust to the title content:

- Current behaviour
![Captura desde 2024-08-05 18-48-36](https://github.com/user-attachments/assets/16c13727-e8de-42a2-be1b-a62d7c9a5c75)

- Previous behaviour
![imagen](https://github.com/user-attachments/assets/4ee7d17f-c3f9-434b-bc4d-31e76aaf2645)

(I'm using a floating bar theme, it probably looks ok in a default bar)

**Comment by Wedaxi** [comment]
I have a fix but I can't create a PR 😅
Allowing the width percentage to go to 0, and use that as a default width value:
```
if (this._settings.get_int('indicator-width') == 0) {
    this._indicator.set_width(-1)
} else {
    this._indicator.set_width(Main.panel.width * this._settings.get_int('indicator-width') * 0.004);
}
```

**Comment by fthx** [comment]
That's clearer this way.
https://github.com/fthx/window-title-is-back/commit/69f7c7d9d9cbce44b22808e1bad8a749e6f22fe7
