### ISSUE TITLE
Too much space unused 

### ISSUE THREAD

**Issue by ThrPaacj** [fthx/window-title-is-back#22]
When I try to use different font for my entire system there is too much space between the text that is displayed by the extensions.
Here a screen of it:
![Screenshot from 2024-08-10 23-48-18](https://github.com/user-attachments/assets/10dff76b-53fe-4967-8c77-657818aff250)

And this is with default gnome font:
![Screenshot from 2024-08-10 23-50-36](https://github.com/user-attachments/assets/51e356d2-10a1-4ea4-855f-a0ad5820dc26)

**Comment by fthx** [comment]
Please name the fonts you used here.

**Comment by ThrPaacj** [comment]
I use MesloLGS nerd font

**Comment by fthx** [comment]
Sorry I cannot reproduce with any of usual fonts.
Could you take a screenshot of your extension settings?

**Comment by ThrPaacj** [comment]
![Screenshot from 2024-08-12 12-35-30](https://github.com/user-attachments/assets/c9ae20d4-c98e-49da-ae19-21502093dc30)

**Comment by fthx** [comment]
I did not try with the problematic fonts but I did not see any bug testing with different usual fonts.
So that's probably a fonts bug.
