### ISSUE TITLE
[Feature request] Window actions

### ISSUE THREAD

**Issue by Pshemas** [fthx/window-title-is-back#3]
First of all - thank you for bringing this feature back. As I work with multiple monitors and multiple screens I really appreciate an indicator that shows me active window.

It would be awesome if you could enable some extra features in the extension settings:

1. Add window actions on click (menu with pin, minimize, close etc)
2. Option to disable minimize on click - that's the main annoyance I currently have with it 
3. As an extension to idea 1 - maybe displaying minimize / maximize /  close buttons as well?

**Comment by fthx** [comment]
Hi,

I won't make anything "smart" on this extension.
So no extra buttons.
But I make now an option to disable minimizing on click.

**Comment by fthx** [comment]
https://extensions.gnome.org/review/45622
