### ISSUE TITLE
Excellent concept. 

### ISSUE THREAD

**Issue by herp1derp2** [fthx/window-title-is-back#4]
Can you do Menu bar instead of Window-Titile like on MacOS?

**Comment by fthx** [comment]
App menu in GNOME is deprecated, so I won't develop something that will disappear.
The second blocking reason is that these app menu items are way too long (eg. Firefox) to be displayed in the panel's left box.
If you mean the in-app menu like file/edit/... in VS code (eg.), that I don't know how to do that and I guess that's very difficult -- even impossible.
