### ISSUE TITLE
gjs title without any window open

### ISSUE THREAD

**Issue by ciro-mota** [fthx/window-title-is-back#5]
Please, is there any way to ignore the gjs window title that appears even without any window being open on the system?

Arch Linux - GNOME 45 - Wayland.

![Captura de tela de 2023-10-13 15-08-52](https://github.com/fthx/window-title-is-back/assets/57502603/3fb7fa30-d6ad-4e15-a88e-3a914404c870)

**Comment by fthx** [comment]
What are the other extensions you use?

**Comment by ciro-mota** [comment]
These:
![Captura de tela de 2023-10-13 16-13-37](https://github.com/fthx/window-title-is-back/assets/57502603/9f9ffe53-d2e5-46d0-a402-00fbc484777f)

**Comment by fthx** [comment]
Wow ^^
Well, I've already tested with DING as I remembered the way it works and I get some ##@@Ch or like that.
I've a precise idea of what filter is missing, stay tuned...

**Comment by fthx** [comment]
https://github.com/fthx/window-title-is-back/commit/eddf0403f85bb84fd75aa1dffcea4d3564240d01

Feel free to reopen if needed.

**Comment by fthx** [comment]
You should auto get the update soon, but the code change is tiny and you can also try it.

**Comment by fthx** [comment]
FYI

https://github.com/fthx/appmenu-is-back
