### ISSUE TITLE
Add Symbolic Icon 

### ISSUE THREAD

**Issue by muhammad-ans** [fthx/window-title-is-back#6]
Can we have an option to have symbolic icon instead of colored one like in gnome 44.
like this
![image](https://github.com/fthx/window-title-is-back/assets/77329029/dc598f5e-2fcf-4284-abde-738e2bf07130)

**Comment by fthx** [comment]
I'll look at this when possible.

**Comment by fthx** [comment]
https://github.com/fthx/window-title-is-back/commit/f9d213e8c0894f76362d93d9083fa34536cb156b
