### ISSUE TITLE
Title and Icon Disappear When Opening Popup Window in Settings

### ISSUE THREAD

**Issue by hazukieq** [fthx/window-title-is-back#7]
### Description

When opening a popup window in the settings of the application, the title and icon in the left top bar disappear. The title and icon reappear after closing the popup window.

### Current Behavior

The title and icon in the left top bar disappear when opening a popup window in the settings of the application.

### Desired Behavior

The title and icon in the left top bar should remain visible when opening a popup window in the settings of the application.

### Steps to Reproduce

1. Open the settings of the application,Click the `Keyboard` button to open the Keyboard layout settings.

  ![{27825-x-102690547973805}(1).png](https://github.com/fthx/window-title-is-back/assets/77765021/c173dc0b-c333-416e-8d34-0c580464d565)

2. Open a popup window by clicking the `Compose Key` button, the title and icon in the left top bar are hidden.

  ![{27825-x-102715634136032}(1).png](https://github.com/fthx/window-title-is-back/assets/77765021/ad9d0990-391a-4426-8bdb-d098dcb185f0)

3. Observe that the title and icon in the left top bar are come back.

![{27825-x-102690547973805}(1).png](https://github.com/fthx/window-title-is-back/assets/77765021/ee48524e-5446-4c9c-972f-b7cc0fd1a93f)

### Possible Solution

It's possible that there is a bug in the code or a problem with the way the popup window is being displayed. Further investigation is needed to determine the root cause of the issue.

### Additional Context

This issue is occurring on Ubuntu23.10

### Acceptance Criteria

- The title and icon in the left top bar should remain visible when opening a popup window in the settings of the application.

### Related Issues

None.

### Environment

- **OS Name:**                                     Ubuntu 23.10
- **OS Build:**                                    2023-10-16
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.0
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.5.0-9-generic

**Comment by fthx** [comment]
Yes there is a small issue here, for some title less windows, I have to query the parent window.
I look at this.

**Comment by hazukieq** [comment]
> Yes there is a small issue here, for some title less windows, I have to query the parent window.
> I look at this.

thanks！this plugin is so pretty well, and I

**Comment by fthx** [comment]
Ok I ran for reuse the old GS code!
There are tons of corner cases.
https://github.com/fthx/appmenu-is-back

**Comment by fthx** [comment]
FYI I did really solve this one, forgot to update this thread.
